"""schema inicial

Revision ID: 6a7b47a79ccb
Revises: 
Create Date: 2026-07-01 14:22:37.340262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7b47a79ccb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('shirt_number', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('monthly_fee_paid', sa.Boolean(), nullable=False),
    sa.Column('total_goals', sa.Integer(), nullable=False),
    sa.Column('total_assists', sa.Integer(), nullable=False),
    sa.Column('total_games', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_id'), ['id'], unique=False)

    op.create_table('tb_finances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('guest_revenue', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('court_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('misc_expenses', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('accumulated_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_finances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_finances_id'), ['id'], unique=False)

    op.create_table('tb_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('team_white_score', sa.Integer(), nullable=False),
    sa.Column('team_red_score', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_games_id'), ['id'], unique=False)

    op.create_table('tb_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.Enum('basic', 'pro', name='planenum'), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_tb_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tb_users_stripe_customer_id'), ['stripe_customer_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tb_users_stripe_subscription_id'), ['stripe_subscription_id'], unique=False)

    op.create_table('tb_game_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.Enum('Branco', 'Vermelho', name='teamenum'), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['tb_games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_game_players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_game_players_id'), ['id'], unique=False)

    op.create_table('tb_monthly_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finance_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['finance_id'], ['tb_finances.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_monthly_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_monthly_payments_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_monthly_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_monthly_payments_id'))

    op.drop_table('tb_monthly_payments')
    with op.batch_alter_table('tb_game_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_game_players_id'))

    op.drop_table('tb_game_players')
    with op.batch_alter_table('tb_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_users_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_tb_users_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_tb_users_id'))
        batch_op.drop_index(batch_op.f('ix_tb_users_email'))

    op.drop_table('tb_users')
    with op.batch_alter_table('tb_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_games_id'))

    op.drop_table('tb_games')
    with op.batch_alter_table('tb_finances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_finances_id'))

    op.drop_table('tb_finances')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_id'))

    op.drop_table('players')
    # ### end Alembic commands ###
